server:
  port: 8080
spring:
  application:
    name: "E-Commerce-ms"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:postgresql://localhost:5432/ecommerce"
    username: "postgres"
    password: "root"
    driverClassName: org.postgresql.Driver

  jpa:
      databasePlatform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true
  sql:
    init:
      mode: embedded

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  server:
    port: 8082

cors:
  allowed-origins: "*"

springdoc:
  use-management-port: true

jwt:
  secret: "secretsecretsecretsecretsecretsecretsecretsecret"
  expiration: 24